server:
  port: 8087
eureka:
  client:
    serviceUrl:
#      defaultZone: http://${eureka.host}:8000/eureka/
#      defaultZone: http://eureka-service:8000/eureka/
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: order-service
  cloud:
    loadbalancer:
      retry:
        enabled: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://${mysql.address}:3306/sys-user?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    url: jdbc:mysql://localhost:3306/order-service?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 133309
  jpa:
    hibernate:
      ddl-auto: update
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
